name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install cypress --save-dev

  test:
    runs-on: ubuntu-latest
    needs: dependency
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: npx cypress run

