name: Cypress E2E Test

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          npx cypress install

  cypress-tests:
    runs-on: ubuntu-latest
    needs: [checkout, install]
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Run Cypress tests
        run: |
          npx cypress run
        working-directory: ${{ github.workspace }}
