name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  dependency:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install cypress --save-dev

  test:
    runs-on: ubuntu-latest
    needs: dependency
    steps:
      - uses: actions/checkout@v3
      - name: Run Cypress tests
        run: |
          npx cypress run --config-file ./testCascade/cypress.config.js
        working-directory: ${{ github.workspace }}

