name: Cypress E2E Test

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  install:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Install dependencies
        run: npm install cypress --save-dev

  run-test:
    runs-on: ubuntu-latest
    needs: [checkout, install]
    steps:
      - name: Run Cypress tests
        run: npx cypress run
